# 1 Getting data ready
### 1.1 split data into features and labels (independent and dependent variable ) x. y
### 1.2 Filling missing values
### 1.3 Converting data values

In [1]:
#standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
pd.set_option("display.max_columns", None)

In [29]:
df = pd.read_csv("cleanHeartData.csv")

In [30]:
df.head()

,Unnamed: 0,age,sex,resting_blood_pressure,cholestoral,fasting_blood_sugar,Max_heart_rate,exercise_induced_angina,oldpeak,target
0,0,52,1,125,212,0,168,0,1.0,0
1,1,53,1,140,203,1,155,1,3.1,0
2,2,70,1,145,174,0,125,1,2.6,0
3,3,61,1,148,203,0,161,0,0.0,0
4,4,62,0,138,294,1,106,0,1.9,0

In [4]:
x = df.drop(['target'],axis=1)    # features

In [5]:
y = df['target']                   #label

In [6]:
x.head()

,Unnamed: 0,age,sex,resting_blood_pressure,cholestoral,fasting_blood_sugar,Max_heart_rate,exercise_induced_angina,oldpeak
0,0,52,1,125,212,0,168,0,1.0
1,1,53,1,140,203,1,155,1,3.1
2,2,70,1,145,174,0,125,1,2.6
3,3,61,1,148,203,0,161,0,0.0
4,4,62,0,138,294,1,106,0,1.9

In [7]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.25)

In [11]:
x_test.shape,x_train.shape      # 76 + 29 = 302

((76, 9), (226, 9))

In [12]:
df.shape

(302, 10)

In [13]:
x_train.dtypes

Unnamed: 0                   int64
age                          int64
sex                          int64
resting_blood_pressure       int64
cholestoral                  int64
fasting_blood_sugar          int64
Max_heart_rate               int64
exercise_induced_angina      int64
oldpeak                    float64
dtype: object

In [31]:
df=pd.read_csv('HeartDiseaseTrain-Test.csv')

In [32]:
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [16]:
df.dtypes

age                                int64
sex                               object
chest_pain_type                   object
resting_blood_pressure             int64
cholestoral                        int64
fasting_blood_sugar               object
rest_ecg                          object
Max_heart_rate                     int64
exercise_induced_angina           object
oldpeak                          float64
slope                             object
vessels_colored_by_flourosopy     object
thalassemia                       object
target                             int64
dtype: object

In [17]:
df["chest_pain_type"].unique()

array(['Typical angina', 'Atypical angina', 'Non-anginal pain',
       'Asymptomatic'], dtype=object)

In [18]:
#encoding 'Typical angina', 'Atypical angina', 'Non-anginal pain','Asymptomatic' 
pd.get_dummies(df["chest_pain_type"])
df["chest_pain_type"] = df["chest_pain_type"].map({'Typical angina': 1 ,
                                                   'Atypical angina': 2,
                                                   'Non-anginal pain' : 3,
                                                   'Asymptomatic' : 4
                                                  })

In [19]:
#encoding male and female
pd.get_dummies(df['sex'])
df['sex'] = df['sex'].map({'Male': 1 , 'Female':0})

In [20]:
# encoding fasting blood suger
pd.get_dummies(df['fasting_blood_sugar'])
df['fasting_blood_sugar'] = df['fasting_blood_sugar'].map({'Lower than 120 mg/ml':0 ,
                                                          'Greater than 120 mg/ml':1})

In [21]:
#encoding rest_ecg
pd.get_dummies(df['rest_ecg'])
df['rest_ecg']=df['rest_ecg'].map({'Normal':0 ,'Left ventricular hypertrophy':1 ,
                                  'ST-T wave abnormality':2})

In [22]:
#encoding exercise_induced_angina
pd.get_dummies(df['exercise_induced_angina'])
df['exercise_induced_angina'] = df['exercise_induced_angina'].map({'Yes': 1 , 'No': 0})

In [23]:
# encoding slope
pd.get_dummies(df['slope'])
df['slope'] = df['slope'].map({'Flat':0 ,'Upsloping':1,'Downsloping':2 })

In [24]:
# encoding vessels_colored_by_flourosopy 
pd.get_dummies(df['vessels_colored_by_flourosopy'])
df['vessels_colored_by_flourosopy'] = df['vessels_colored_by_flourosopy'].map({'Zero':0,'Four':4,
                                                                              'One':1,'Two':2,'Three':3})

In [25]:
# encoding thalassemia
pd.get_dummies(df['thalassemia'])
df['thalassemia']=df['thalassemia'].map({'No':0 , 'Normal' : 2 ,'Fixed Defect':1,'Reversable Defect':3})

In [26]:
df['thalassemia'].unique()  # inspecting unique values in a column

array([3, 1, 2, 0], dtype=int64)

In [33]:
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [34]:
df.dtypes

age                                int64
sex                               object
chest_pain_type                   object
resting_blood_pressure             int64
cholestoral                        int64
fasting_blood_sugar               object
rest_ecg                          object
Max_heart_rate                     int64
exercise_induced_angina           object
oldpeak                          float64
slope                             object
vessels_colored_by_flourosopy     object
thalassemia                       object
target                             int64
dtype: object

In [35]:
df.to_csv("cleanHeartData1.csv")

In [36]:
x = df.drop(['target'] , axis =1)

In [37]:
x.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect

In [38]:
y= df['target']

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.3)

In [40]:
#build ml model 
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor()
clf.fit(x_train, y_train)
clf.score(x_test,y_test)

ValueError: could not convert string to float: 'Male'

In [2]:
df_h= pd.read_csv('HeartDiseaseTrain-Test.csv')

In [3]:
df_h.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [4]:
x =df_h.drop('target',axis=1)
y=df_h['target']

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
features = ['sex','chest_pain_type','fasting_blood_sugar','rest_ecg','exercise_induced_angina','slope','vessels_colored_by_flourosopy','thalassemia']
hottie = OneHotEncoder()

transformer = ColumnTransformer([("One_hotti",hottie,features)],remainder= 'passthrough')
transformer_x =transformer.fit_transform(x)
pd.DataFrame(transformer_x)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,52.0,125.0,212.0,168.0,1.0
1,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,53.0,140.0,203.0,155.0,3.1
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,70.0,145.0,174.0,125.0,2.6
3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,61.0,148.0,203.0,161.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,62.0,138.0,294.0,106.0,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,59.0,140.0,221.0,164.0,0.0
1021,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,60.0,125.0,258.0,141.0,2.8
1022,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,47.0,110.0,275.0,118.0,1.0
1023,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,50.0,110.0,254.0,159.0,0.0
1024,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,54.0,120.0,188.0,113.0,1.4

In [6]:
transformed_new = pd.get_dummies(df_h[["sex","chest_pain_type","fasting_blood_sugar","rest_ecg","exercise_induced_angina","slope","vessels_colored_by_flourosopy","thalassemia"]])
transformed_new

,sex_Female,sex_Male,chest_pain_type_Asymptomatic,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,fasting_blood_sugar_Greater than 120 mg/ml,fasting_blood_sugar_Lower than 120 mg/ml,rest_ecg_Left ventricular hypertrophy,rest_ecg_Normal,...,slope_Upsloping,vessels_colored_by_flourosopy_Four,vessels_colored_by_flourosopy_One,vessels_colored_by_flourosopy_Three,vessels_colored_by_flourosopy_Two,vessels_colored_by_flourosopy_Zero,thalassemia_Fixed Defect,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,False,True,False,False,False,True,False,True,False,False,...,False,False,False,False,True,False,False,False,False,True
1,False,True,False,False,False,True,True,False,False,True,...,True,False,False,False,False,True,False,False,False,True
2,False,True,False,False,False,True,False,True,False,False,...,True,False,False,False,False,True,False,False,False,True
3,False,True,False,False,False,True,False,True,False,False,...,False,False,True,False,False,False,False,False,False,True
4,True,False,False,False,False,True,True,False,False,False,...,False,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,False,True,False,True,False,False,False,True,False,False,...,False,False,False,False,False,True,True,False,False,False
1021,False,True,False,False,False,True,False,True,False,True,...,False,False,True,False,False,False,False,False,False,True
1022,False,True,False,False,False,True,False,True,False,True,...,False,False,True,False,False,False,True,False,False,False
1023,True,False,False,False,False,True,False,True,False,True,...,False,False,False,False,False,True,True,False,False,False
1024,False,True,False,False,False,True,False,True,False,False,...,False,False,True,False,False,False,False,False,False,True

In [7]:
df_h.columns

Index(['age', 'sex', 'chest_pain_type', 'resting_blood_pressure',
       'cholestoral', 'fasting_blood_sugar', 'rest_ecg', 'Max_heart_rate',
       'exercise_induced_angina', 'oldpeak', 'slope',
       'vessels_colored_by_flourosopy', 'thalassemia', 'target'],
      dtype='object')

In [8]:
df_h.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [9]:
df_h.columns

Index(['age', 'sex', 'chest_pain_type', 'resting_blood_pressure',
       'cholestoral', 'fasting_blood_sugar', 'rest_ecg', 'Max_heart_rate',
       'exercise_induced_angina', 'oldpeak', 'slope',
       'vessels_colored_by_flourosopy', 'thalassemia', 'target'],
      dtype='object')

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
x_train,x_test,y_train,y_test = train_test_split(transformer_x,y, test_size=0.2)
prediction = RandomForestRegressor()
prediction.fit(x_train,y_train)

RandomForestRegressor()

In [14]:
prediction.score(x_test,y_test)

0.9696661324786324

In [39]:
df = pd.read_csv("mising_data_md.csv")

In [40]:
df.isna().sum()

Brand          0
Model          0
Price          1
Battery_mAh    1
Storage_GB     1
RAM_GB         2
Weight_g       2
Rating         1
dtype: int64

In [41]:
df.isna().sum()

Brand          0
Model          0
Price          1
Battery_mAh    1
Storage_GB     1
RAM_GB         2
Weight_g       2
Rating         1
dtype: int64

In [44]:
df['Battery_mAh'].fillna("missing",inplace=True)
df['Storage_GB'].fillna(np.mean(df['Storage_GB']), inplace=True)

C:\Users\AL Rehman Computer\AppData\Local\Temp\ipykernel_9860\2913607388.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'missing' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Battery_mAh'].fillna("missing",inplace=True)
C:\Users\AL Rehman Computer\AppData\Local\Temp\ipykernel_9860\2913607388.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Storage_GB'].fillna(np.mean(df['Storage_GB']), inplace=True)

In [45]:
df.isnull().sum()

Brand          0
Model          0
Price          1
Battery_mAh    0
Storage_GB     0
RAM_GB         2
Weight_g       2
Rating         1
dtype: int64

In [46]:
df.dropna(inplace=True)

In [47]:
df.isna().sum()

Brand          0
Model          0
Price          0
Battery_mAh    0
Storage_GB     0
RAM_GB         0
Weight_g       0
Rating         0
dtype: int64

In [49]:
df

     Brand     Model  Price Battery_mAh  Storage_GB  RAM_GB  Weight_g  Rating
3   Realme  Realme 8  $229       5000.0  128.000000     6.0     177.0     4.4
5     Vivo       Y21  $180       5000.0   64.000000     4.0     182.0     4.1
6  OnePlus     9 Pro  $969       4500.0   99.555556    12.0     197.0     4.6
8    Tecno  Camon 17  $150       5000.0   64.000000     4.0     190.0     3.9

In [54]:
df['Price'] = df["Price"].str.replace(r"[$]","",regex=True,).astype(int)

In [55]:
df

     Brand     Model  Price Battery_mAh  Storage_GB  RAM_GB  Weight_g  Rating
3   Realme  Realme 8    229      5000.0  128.000000     6.0     177.0     4.4
5     Vivo       Y21    180      5000.0   64.000000     4.0     182.0     4.1
6  OnePlus     9 Pro    969      4500.0   99.555556    12.0     197.0     4.6
8    Tecno  Camon 17    150      5000.0   64.000000     4.0     190.0     3.9

In [56]:
x=df.drop('Price',axis=1)
y=df["Price"]

In [57]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
features = ['Brand','Model']
hottie = OneHotEncoder()

transformer = ColumnTransformer([("One_hotti",hottie,features)],remainder= 'passthrough')
transformer_x =transformer.fit_transform(x)
pd.DataFrame(transformer_x)

    0    1    2    3    4    5    6    7       8          9     10     11   12
0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  5000.0      128.0   6.0  177.0  4.4
1  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  5000.0       64.0   4.0  182.0  4.1
2  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  4500.0  99.555556  12.0  197.0  4.6
3  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  5000.0       64.0   4.0  190.0  3.9

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
x_train,x_test,y_train,y_test = train_test_split(transformer_x,y, test_size=0.2)
prediction = RandomForestRegressor()
prediction.fit(x_train,y_train)

RandomForestRegressor()

In [59]:
prediction.score(x_test,y_test)

D:\Anaconda\Lib\site-packages\sklearn\metrics\_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

nan

Use a bigger test set

# 2nd Method to fillna by sklearn

In [60]:
df= pd.read_csv("mising_data_md.csv")

In [61]:
df

,Brand,Model,Price,Battery_mAh,Storage_GB,RAM_GB,Weight_g,Rating
0,Samsung,Galaxy S21,NaN,4000.0,128.0,8.0,169.0,4.5
1,Apple,iPhone 13,$899,3227.0,128.0,4.0,NaN,4.7
2,Xiaomi,Redmi Note 10,$199,5000.0,64.0,NaN,178.0,4.3
3,Realme,Realme 8,$229,5000.0,128.0,6.0,177.0,4.4
4,Oppo,Reno6,$449,NaN,128.0,8.0,173.0,NaN
5,Vivo,Y21,$180,5000.0,64.0,4.0,182.0,4.1
6,OnePlus,9 Pro,$969,4500.0,NaN,12.0,197.0,4.6
7,Infinix,Zero X,$250,4500.0,128.0,8.0,NaN,4.0
8,Tecno,Camon 17,$150,5000.0,64.0,4.0,190.0,3.9
9,Nokia,G20,$160,5050.0,64.0,NaN,197.0,3.8

In [62]:
df.isnull().sum()

Brand          0
Model          0
Price          1
Battery_mAh    1
Storage_GB     1
RAM_GB         2
Weight_g       2
Rating         1
dtype: int64

In [63]:
df.dropna(subset=["Price"],inplace=True)
df.isnull().sum()

Brand          0
Model          0
Price          0
Battery_mAh    1
Storage_GB     1
RAM_GB         2
Weight_g       2
Rating         1
dtype: int64

In [65]:
df['Price'] = df['Price'].str.replace(r'[$]',"",regex=True).astype(int)

In [69]:
#split x and y
x = df.drop("Price", axis= 1)
y = df["Price"]

In [75]:
x

     Brand          Model  Battery_mAh  Storage_GB  RAM_GB  Weight_g  Rating
1    Apple      iPhone 13       3227.0       128.0     4.0       NaN     4.7
2   Xiaomi  Redmi Note 10       5000.0        64.0     NaN     178.0     4.3
3   Realme       Realme 8       5000.0       128.0     6.0     177.0     4.4
4     Oppo          Reno6          NaN       128.0     8.0     173.0     NaN
5     Vivo            Y21       5000.0        64.0     4.0     182.0     4.1
6  OnePlus          9 Pro       4500.0         NaN    12.0     197.0     4.6
7  Infinix         Zero X       4500.0       128.0     8.0       NaN     4.0
8    Tecno       Camon 17       5000.0        64.0     4.0     190.0     3.9
9    Nokia            G20       5050.0        64.0     NaN     197.0     3.8

In [72]:
#imputation
#filling data with sk learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#fill catogorical values with misssing and numeric values with mean
#cat_features = SimpleImputer(strategy="constant", fill_value='missing')
num_features = SimpleImputer(strategy="mean")

#define columns 
num_feature = ['Battery_mAh','Storage_GB','RAM_GB','Weight_g','Rating']
imputer = ColumnTransformer([('num_features',num_features,num_feature)])
filled_x = imputer.fit_transform(x)
filled_x

array([[3.22700000e+03, 1.28000000e+02, 4.00000000e+00, 1.84857143e+02,
        4.70000000e+00],
       [5.00000000e+03, 6.40000000e+01, 6.57142857e+00, 1.78000000e+02,
        4.30000000e+00],
       [5.00000000e+03, 1.28000000e+02, 6.00000000e+00, 1.77000000e+02,
        4.40000000e+00],
       [4.65962500e+03, 1.28000000e+02, 8.00000000e+00, 1.73000000e+02,
        4.22500000e+00],
       [5.00000000e+03, 6.40000000e+01, 4.00000000e+00, 1.82000000e+02,
        4.10000000e+00],
       [4.50000000e+03, 9.60000000e+01, 1.20000000e+01, 1.97000000e+02,
        4.60000000e+00],
       [4.50000000e+03, 1.28000000e+02, 8.00000000e+00, 1.84857143e+02,
        4.00000000e+00],
       [5.00000000e+03, 6.40000000e+01, 4.00000000e+00, 1.90000000e+02,
        3.90000000e+00],
       [5.05000000e+03, 6.40000000e+01, 6.57142857e+00, 1.97000000e+02,
        3.80000000e+00]])

In [76]:
x.columns

Index(['Brand', 'Model', 'Battery_mAh', 'Storage_GB', 'RAM_GB', 'Weight_g',
       'Rating'],
      dtype='object')

In [80]:
phone_data = pd.DataFrame(filled_x,columns=['Brand', 'Model', 'Battery_mAh', 'Storage_GB', 'RAM_GB', 'Weight_g','Rating'])

ValueError: Shape of passed values is (9, 5), indices imply (9, 7)

In [74]:
phone_data

          0      1          2           3      4
0  3227.000  128.0   4.000000  184.857143  4.700
1  5000.000   64.0   6.571429  178.000000  4.300
2  5000.000  128.0   6.000000  177.000000  4.400
3  4659.625  128.0   8.000000  173.000000  4.225
4  5000.000   64.0   4.000000  182.000000  4.100
5  4500.000   96.0  12.000000  197.000000  4.600
6  4500.000  128.0   8.000000  184.857143  4.000
7  5000.000   64.0   4.000000  190.000000  3.900
8  5050.000   64.0   6.571429  197.000000  3.800

# Model Selection

In [9]:
from sklearn.datasets import fetch_california_housing
c_housing = fetch_california_housing()
c_housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [13]:
# Convert to DataFrame
df = pd.DataFrame(c_housing.data, columns=c_housing.feature_names)
# Add target column
df["target"] = c_housing['target']

# Show the first few rows
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [14]:
df.shape

(20640, 9)

In [15]:
len(df)

20640

### use sklearn estimator choice documentation on google

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
#to produce similar results for others
np.random.seed()
#create data 
x = df.drop('target',axis=1)
y = df['target']
# split train text 
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2)
# use instantiate , Ridge model
reg_model = Ridge()
model = reg_model.fit(x_train,y_train)
model.score(x_test,y_test)

0.5717774705090733

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
#to produce similar results for others
np.random.seed()
#create data 
x = df.drop('target',axis=1)
y = df['target']
# split train text 
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2)
# use instantiate , Ridge model
rfr = Ridge()
model = rfr.fit(x_train,y_train)
model.score(x_test,y_test)

0.6111354805791842

# Choosing Estimator  for classification Problem

In [3]:
df = pd.read_csv('cleanHeartData1.csv')

In [4]:
df.head()

,Unnamed: 0,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,0,52,1,1,125,212,0,2,168,0,1.0,2,2,3,0
1,1,53,1,1,140,203,1,0,155,1,3.1,1,0,3,0
2,2,70,1,1,145,174,0,2,125,1,2.6,1,0,3,0
3,3,61,1,1,148,203,0,2,161,0,0.0,2,1,3,0
4,4,62,0,1,138,294,1,2,106,0,1.9,0,3,1,0

In [7]:
df = df.drop('Unnamed: 0', axis = 1)

In [8]:
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,1,1,125,212,0,2,168,0,1.0,2,2,3,0
1,53,1,1,140,203,1,0,155,1,3.1,1,0,3,0
2,70,1,1,145,174,0,2,125,1,2.6,1,0,3,0
3,61,1,1,148,203,0,2,161,0,0.0,2,1,3,0
4,62,0,1,138,294,1,2,106,0,1.9,0,3,1,0

In [9]:
df.duplicated().sum()

723

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

0

In [13]:
df.shape

(302, 14)

In [16]:
# imported linear svc model
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split

#spliting data 
x = df.drop('target',axis=1)
y = df['target']

#split train test
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3)

# instinciate model
lsvc = LinearSVC()
model = lsvc.fit(x_train,y_train)

# model score
model.score(x_test,y_test)

0.8351648351648352

In [18]:
from sklearn.ensemble import RandomForestClassifier
# the train test split is already defined above

#split data 
x = df.drop('target',axis=1)
y = df['target']

#split train test
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3)

# model fitting
rfc = RandomForestClassifier()
model = rfc.fit(x_train,y_train)

# model score 
model.score(x_test,y_test)

0.8571428571428571

### in classification you should tell only Yes or no.
### in regression you will predict a number only.
### if you have structured data use / prefere ensamble method
### if you have unstructured data use / prefer deep learning\